# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

version: '3'
services:
  python-env:
    build:
      context: .
      args:
        PROJECT: ${PROJECT}
    image: pangolin/${PROJECT}-py
    container_name: pangopy-${PROJECT}
    environment:
      MONGODB_PASSWORD: ${MONGO_PWD}
      CONF_PATH: "/workspace/config"
      AIRDROP_CONF: ${AIRDROP_CONF}
    command: [ "tail", "-f", "./requirements.txt"]
    volumes:
      - ./${PROJECT}:/workspace/
      - ../config:/workspace/config
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_URI: ${MONGO_URI}
    volumes:
      - mongodbdata:/data/db/
      - ./outputs:/workspace/outputs
    ports:
      - "27017:27017"
#    command: [ "-f", "/etc/mongod.conf" ]
volumes:
  mongodbdata: